// <auto-generated />
using AdminSiste.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminSiste.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516214022_CreateServicoModule")]
    partial class CreateServicoModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AdminSiste.Models.Cliente.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vendedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AdminSiste.Models.Cliente.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelefoneCelular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TelefoneComercial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("AdminSiste.Models.Cliente.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EstoqueMaximo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EstoqueMinimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Preco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorCustoMedio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorDespesasAcessorias")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ValorOutrasDespesas")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .IsUnique();

                    b.ToTable("Precos");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DetalhesId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoProdutoId")
                        .HasColumnType("int");

                    b.Property<bool>("MovimentaEstoque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<bool>("PossuiComposicao")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PossuiNotaFiscal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PossuiVariacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("QuantidadeSaida")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UnidadeEntradaId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnidadeSaidaId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DetalhesId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.ProdutoDetalhes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ComercializavelPDV")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Comprimento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Largura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("VendidoSeparadamente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoDetalhes");
                });

            modelBuilder.Entity("AdminSiste.Models.Servico.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArquivoUpload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AtividadeId")
                        .HasColumnType("int");

                    b.Property<bool>("BeneficioMunicipal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("ConstrucaoCivil")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DescontarDeducoes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DescontarImpostos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ImpostosId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeId");

                    b.HasIndex("ImpostosId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("AdminSiste.Models.Servico.ServicoAtividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtividadeServico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CNAE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoNBS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoServico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoTributacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescricaoAtividade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ServicoAtividades");
                });

            modelBuilder.Entity("AdminSiste.Models.Servico.ServicoImpostos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PercentualCOFINS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualCSLL")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualINSS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualIR")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualISS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PercentualPIS")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("ServicoImpostos");
                });

            modelBuilder.Entity("AdminSiste.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AdminSiste.Models.Cliente.Contato", b =>
                {
                    b.HasOne("AdminSiste.Models.Cliente.Cliente", "Cliente")
                        .WithMany("Contatos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AdminSiste.Models.Cliente.Endereco", b =>
                {
                    b.HasOne("AdminSiste.Models.Cliente.Cliente", "Cliente")
                        .WithMany("Enderecos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Estoque", b =>
                {
                    b.HasOne("AdminSiste.Models.Produto.Produto", "Produto")
                        .WithOne("Estoque")
                        .HasForeignKey("AdminSiste.Models.Produto.Estoque", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Preco", b =>
                {
                    b.HasOne("AdminSiste.Models.Produto.Produto", "Produto")
                        .WithOne("Preco")
                        .HasForeignKey("AdminSiste.Models.Produto.Preco", "ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Produto", b =>
                {
                    b.HasOne("AdminSiste.Models.Produto.ProdutoDetalhes", "Detalhes")
                        .WithMany()
                        .HasForeignKey("DetalhesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("AdminSiste.Models.Servico.Servico", b =>
                {
                    b.HasOne("AdminSiste.Models.Servico.ServicoAtividade", "Atividade")
                        .WithMany()
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminSiste.Models.Servico.ServicoImpostos", "Impostos")
                        .WithMany()
                        .HasForeignKey("ImpostosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Impostos");
                });

            modelBuilder.Entity("AdminSiste.Models.Cliente.Cliente", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("AdminSiste.Models.Produto.Produto", b =>
                {
                    b.Navigation("Estoque")
                        .IsRequired();

                    b.Navigation("Preco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
