version: '3.9'

services:
  adminsite:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__HomologacaoConnection=server=mysql-dev;port=3306;database=homologacao;user=hmg;password=010101
    networks:
      - pedidos-network

networks:
  pedidos-network:
    external: true
    name: pedidos-network
